version: "3.8"

services:
  mysql:
    container_name: db_contact_management
    image: mysql:8.3
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_contact_management
    volumes:
      - volume_contact_management:/var/lib/mysql
    networks:
      - net_contact_management
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 20s
      retries: 10

  api:
    container_name: contact_mgmt_api
    image: ghcr.io/malllvinnn/contact-management-restful-api-ts:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      PORT: 3000
      CLIENT_URL: ${CLIENT_URL}
    networks:
      - net_contact_management

volumes:
  volume_contact_management:

networks:
  net_contact_management:
